load(":native-toolchains.bzl", "native_kotlin_toolchain")

exports_files(["compile.mjs"])

exports_files(["native_artifacts.bzl", "native_artifacts.py"])

exports_files(["native.bzl", "codegen.mjs", "native-dependencies.bzl", "native-dependencies.py", "native-toolchains.bzl"])
native_kotlin_toolchain(name = "kotlin_toolchain")
